### ISSUE TITLE
Offer a software engineering apprentice internship program for students at UTM taking a gap year

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/org#29]
Some students taking a gap year from university could get great value from apprenticing as a software engineer under me. 

### Offering details

- Hands on software engineering learning
- Ownership of a project
- Personal mentorship with 1:1 meetings every 2 weeks

### Implementation Checklist

- [ ] Advertise on the website
- [ ] Create digital marketing materials 
- [ ] Figure out a price structure 
- [ ] Break down the hourly commitment required of me

I don't think I can take on more than 3 apprentice interns given that I'm going back to school.

**Comment by ninaricci29** [comment]
We will revisit this near 2021.
