### ISSUE TITLE
Research a possible pre-commit quality check for pull requests 

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/org#36]
Research automated and manual checklists to ensure commits are of a certain quality.

**Comment by AaronCGoidel** [comment]
In the past, I’ve used [Husky](https://github.com/typicode/husky) for pre-commit hooks. I’d recommend checking that out.

**Comment by ArsalaBangash** [comment]
@AaronCGoidel Do you have the bandwidth to configure Husky on Grey Software's repos?

**Comment by AaronCGoidel** [comment]
Sure, doesn't seem like too bad an undertaking. What hooks would we like set up?

**Comment by ArsalaBangash** [comment]
Formatting: Prettier
Linting: ESLint 
Scripts: npm run build or npm run test if either exists. For most of our web projects, The build command exists
