### ISSUE TITLE
Organize and Develop the Grey Software community

### ISSUE THREAD

**Issue by ninaricci29** [grey-software/org#44]
- [x] Create channels on discord that will help instigate meaningful conversations
- [ ] Propose and invite students from other potential server partners to join our server
- [x] Create a Reddit account

**Comment by ArsalaBangash** [comment]
What is the value we are looking to gain from a Reddit account?

**Comment by AaronCGoidel** [comment]
I believe it’s a good idea to secure social media handles, no matter if we will use them. We want to be the ones to own the name we want to use online across all platforms, just in case.

**Comment by ArsalaBangash** [comment]
Nina also mentioned that Reddit is the first place she goes to for advice, so for those like Nina looking for an OSS dev community to be a part, we can direct them!

**Comment by ArsalaBangash** [comment]
I fear we may have to create a Reddit Focus extension lool

**Comment by ArsalaBangash** [comment]
I'm closing the second point in this issue because out UTM server partners and The Futurist Foundation's list of channels like Open Source and Skill Sharing have agreed to help out in differing capacities.
