### ISSUE TITLE
⚙️ Task: Add icons to our discord channels

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/org#56]
### Motivation 🏁

Adding icons to our channels would make our Discord server look better, like The Futurist Foundation

<img width="228" alt="image" src="https://user-images.githubusercontent.com/19757203/97093138-f05a7c00-1662-11eb-9130-16226c217d3e.png">

### Details 🛠️

Let's look for premium icons from Flaticon to set our Discord server apart.

**Comment by ninaricci29** [comment]
Its only restricted to emojis. I cant upload Vue/CSS/HTML/Toonin/Projects/etc icons.
